### PR TITLE
ATmega128 support

### PR DESCRIPTION
**Pull request by nathancheek**
These changes enable the ATmega128 design to compile and successfully run a basic blink deployment (with F Prime GDS commanding and telemetry). This builds off the ranlib update in PR #29.

There are 4 main changes:
* `TimerOne` library updated with latest patches, AVR builds made to point to the local patched `TimerOne` library instead of the upstream unpatched version (which doesn't support ATmega128), and now-unnecessary `TimerOne`-related compiler flags removed
* Addition of compiler flags which optimize for flash size
* New `ARDUINO_BOARD_OPTIONS` cmake variable which works with the `arduino-cli-cmake-wrapper` to pass `--board-options` to `arduino-cli` (necessary in this case for specifying the clockspeed)
* New `ARDUINO_LINKER_FLAGS` cmake variable which allows for custom linker flags (necessary in this case for telling the linker to place `.data`, `.bss`, and the heap in external SRAM, leaving internal SRAM dedicated to the stack [0])

[0] https://www.nongnu.org/avr-libc/user-manual/malloc.html#malloc_tunables

### CODE REVIEW

**Review by ethancheez — APPROVED** [review]

**Comment by LeStarch** [comment]
Has more work been done since this PR, or should I review this one?

**Review by LeStarch — APPROVED** [review]

**Comment by nathancheek** [comment]
No more work had been done, thanks for reviewing and merging. We have an ATmega128 blink reference (with fprime-gds support) working off of the changes you just merged. I will try to make that deployment public soon.

**Comment by ethancheez** [comment]
@nathancheek 
I just realized, there is no release of your `refactor-build-properties` work correct? I had to do a manual install of the `arduino-cli-cmake-wrapper` via the GitHub repo instead of through `pip`.

Otherwise, I get an error when generating: 
```
usage: arduino-cli-wrapper [-h] [--debug] -b BOARD [-d] [-g] [-i]
                           [-l [LIBRARIES ...]] [-c [COPY ...]]
                           [--properties [PROPERTIES ...]] [-p] -o OUTPUT
                           [-j JSON_FILE]
arduino-cli-wrapper: error: unrecognized arguments: --board-options
```

The `--board-options` flag is not implemented in the `pip` release (v0.1.0).

**Comment by nathancheek** [comment]
Ah you are correct. @SterlingPeet can we get those changes to [arduino-cli-cmake-wrapper](https://github.com/SterlingPeet/arduino-cli-cmake-wrapper) merged into main with a new release that can be installed via pip?

**Comment by SterlingPeet** [comment]
This is on my todo list, should percolate up to the top in the next two weeks.  Just cleaning up some release-support stuff.  @ethancheez you can install the ``refactor-tooling-cleanup`` branch for the latest changes that are due for release.

**Comment by SterlingPeet** [comment]
@LeStarch That seems fine, just publish it as a patch or alpha release so we don't confuse the version numbering.

**Pull request merged**
